---
title: "Regresja liniowa i regresja logistyczna"
author: "Paweł Wieczyński"
format: html
editor: visual
---

## Quarto

```{r}
library(tidyverse)
library(broom)
```

## Regresja liniowa

### Przykład z jedną zmienną objaśniającą

```{r}
data(cars)
summary(cars)
```

```{r}
cars$speed = cars$speed * 1.609344
cars$dist = cars$dist * 0.3048
summary(cars)
```

```{r}
ggplot(cars, aes(x = speed, y = dist)) +
  geom_point()

cars %>%
  pivot_longer(
    cols = 1:2
    , names_to = 'Variable'
    , values_to = 'Value') %>%
  ggplot(aes(x = Variable, y = Value, fill = Variable)) +
  geom_boxplot() +
  theme(legend.position = 'none')
```

```{r}
model_1 = lm(dist ~ speed, data = cars)
model_2 = lm(dist ~ I(speed^2), data = cars)
```

```{r}
summary(model_1)
summary(model_2)
```

```{r}
ggplot(cars, aes(x = speed, y = dist)) +
  geom_point() +
  geom_smooth(formula = 'y ~ x', method = 'lm', se = FALSE) +
  geom_smooth(formula = 'y ~ I(x^2)', method = 'lm', se = FALSE, color = 'red')
```

```{r}
cars_model_1 = augment(model_1)
cars_model_2 = augment(model_2)

ggplot(cars_model_1, aes(.resid)) +
  geom_histogram(color = 'white', bins = 10)

ggplot(cars_model_2, aes(.resid)) +
  geom_histogram(color = 'white', bins = 10)
```

```{r}
new_data = data.frame(speed = c(30, 50, 80))
predict(model_1, newdata = new_data)
predict(model_2, newdata = new_data)
```
